package main

var weirdSyms = map[rune]string{
	' ':  "space",
	'!':  "exclam",
	'@':  "at",
	'#':  "numbersign",
	'$':  "dollar",
	'%':  "percent",
	'^':  "asciicircum",
	'&':  "ampersand",
	'*':  "asterisk",
	'(':  "parenleft",
	')':  "parenright",
	'[':  "bracketleft",
	']':  "bracketright",
	'{':  "braceleft",
	'}':  "braceright",
	'-':  "minus",
	'_':  "underscore",
	'=':  "equal",
	'+':  "plus",
	'\\': "backslash",
	'|':  "bar",
	';':  "semicolon",
	':':  "colon",
	'\'': "quoteright",
	'"':  "quotedbl",
	'<':  "less",
	'>':  "greater",
	',':  "comma",
	'.':  "period",
	'/':  "slash",
	'?':  "question",
	'`':  "quoteleft",
	'~':  "asciitilde",
}
